### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by nathancarter209** [SudeepAcharjee/Never_more#11]
Please think of a new logo because this logo isn't going to cut it and this logo looks really unprofessional and too childish.
The new logo must be small and probably in 100x100 pixels.

**Comment by SudeepAcharjee** [comment]
Yes..One of my friend is working on that...will be available soon
@nathancarter209

**Comment by nathancarter209** [comment]
> Yes..One of my friend is working on that...will be available soon
> @nathancarter209

Then add him on this issue so we will have a record.
@SudeepAcharjee

**Comment by SudeepAcharjee** [comment]
> He is not into github . He is an artist as well make digital arts and logos

**Comment by nathancarter209** [comment]
Ojay then,
