### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by nathancarter209** [SudeepAcharjee/Never_more#12]
Need to change the UI, it's not even, considered looking into this link below for an idea
https://www.instagram.com/p/CnjiCiwN5-I/

**Comment by SudeepAcharjee** [comment]
> Need to change the UI, it's not even, considered looking into this link below for an idea https://www.instagram.com/p/CnjiCiwN5-I/

Go ahead ..I ll be helping you ..I think we will need more Collaborators to change the UI and for now we should more focus in completing the base of the web site. Like adding the contents ..videos .

**Comment by nathancarter209** [comment]
well okay, then gotcha.
